---
# Source: kube-opex-analytics/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-opex-analytics
  namespace: kube-opex-analytics
  labels:
    helm.sh/chart: kube-opex-analytics-2022-02-02-740796d
    app.kubernetes.io/name: kube-opex-analytics
    app.kubernetes.io/instance: kube-opex-analytics
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    app: kube-opex-analytics
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5483
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kube-opex-analytics
    app.kubernetes.io/instance: kube-opex-analytics
