---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-opex-analytics
  namespace: kube-opex-analytics
  labels:
    helm.sh/chart: kube-opex-analytics-2022-02-02-740796d
    app.kubernetes.io/name: kube-opex-analytics
    app.kubernetes.io/instance: kube-opex-analytics
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    app: kube-opex-analytics
spec:
  replicas: 1
  serviceName: kube-opex-analytics
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-opex-analytics
      app.kubernetes.io/instance: kube-opex-analytics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-opex-analytics
        app.kubernetes.io/instance: kube-opex-analytics
    spec:
      securityContext:
        runAsUser: 4583
        fsGroup: 4583
      serviceAccountName: kube-opex-analytics
      restartPolicy: Always
      containers:
        - name: kube-opex-analytics
          image: kube-opex-analytics
          imagePullPolicy: Always
          env:
            - name: "KOA_DB_LOCATION"
              value: "/data/db"
            - name: "KOA_K8S_API_ENDPOINT"
              value: "https://kubernetes.default"
            - name: "KOA_K8S_API_VERIFY_SSL"
              value: "false"
            - name: "KOA_BILLING_CURRENCY_SYMBOL"
              valueFrom:
                configMapKeyRef:
                  key: KOA_BILLING_CURRENCY_SYMBOL
                  name: kube-opex-analytics-config
            - name: "KOA_BILLING_HOURLY_RATE"
              valueFrom:
                configMapKeyRef:
                  key: KOA_BILLING_HOURLY_RATE
                  name: kube-opex-analytics-config
            - name: "KOA_COST_MODEL"
              valueFrom:
                configMapKeyRef:
                  key: KOA_COST_MODEL
                  name: kube-opex-analytics-config
          ports:
            - name: http
              containerPort: 5483
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /data/
              name: data-vol
            - mountPath: /koa/static/data/
              name: static-data-vol
      volumes:
      - name: static-data-vol
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
