version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
    - rchakode
  reviewers:
    - rchakode
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  assignees:
    - rchakode
  reviewers:
    - rchakode
