{
 "title": "kube-opex-analytics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Hourly CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "koa_namespace_hourly_usage{resource=\"CPU\"}",
     "legendFormat": "{{  namespace }}"
    }
   ]
  },
  {
   "title": "Hourly Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "koa_namespace_hourly_usage{resource=\"MEMORY\"}",
     "legendFormat": "{{  namespace }}"
    }
   ]
  },
  {
   "title": "Current Day's CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "koa_namespace_daily_usage{resource=\"CPU\"}",
     "legendFormat": "{{  namespace }}"
    }
   ]
  },
  {
   "title": "Current Day's Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "koa_namespace_daily_usage{resource=\"MEMORY\"}",
     "legendFormat": "{{  namespace }}"
    }
   ]
  },
  {
   "title": "Current Month's CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "koa_namespace_monthly_usage{resource=\"CPU\"}",
     "legendFormat": "{{  namespace }}"
    }
   ]
  },
  {
   "title": "Current Month's Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "koa_namespace_monthly_usage{resource=\"MEMORY\"}",
     "legendFormat": "{{  namespace }}"
    }
   ]
  }
 ]
}