apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-opex-analytics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-opex-analytics.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-opex-analytics.fullname" . }}
  labels:
    {{- include "kube-opex-analytics.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  - nodes/stats
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-opex-analytics.fullname" . }}
  labels:
    {{- include "kube-opex-analytics.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-opex-analytics.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-opex-analytics.fullname" . }}
  namespace: {{ .Release.Namespace }}
