---
# Source: kube-opex-analytics/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-opex-analytics
  labels:
    app.kubernetes.io/name: kube-opex-analytics
    app.kubernetes.io/instance: kube-opex-analytics
    app: kube-opex-analytics
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5483
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kube-opex-analytics
    app.kubernetes.io/instance: kube-opex-analytics
