---
apiVersion: v1
kind: Pod
metadata:
  name: "kube-opex-analytics-test-connection"
  labels:
    app.kubernetes.io/name: kube-opex-analytics
    app.kubernetes.io/instance: kube-opex-analytics
spec:
  containers:
    - name: wget
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - echo 'waiting 60s';
          sleep 60;
          wget 'kube-opex-analytics:80';
          echo done;   
  restartPolicy: Never
